import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./app.css";
import MainLayout from "./components/MainLayout";
import SideContextProvider from "./components/context/side-context";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Myccangel",
  description: "Generated by Babylon Coding",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body >
     
        <SideContextProvider>
      <MainLayout>{children}</MainLayout>
     </SideContextProvider>
   
      </body>
    </html>
  );
}
