on:
  push:
    branches:
      - '*'  # Mirror all branches

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Clone Repository with Mirror Flag
        run: |
          git clone --mirror https://github.com/${{ github.repository }}.git
          echo "************************cloned!"
          cd ${{github.event.repository.name}}.git
          echo "*********************************in the directory"
          git remote add upstream https://samHD76:${{ secrets.PAT}}@github.com/samHD76/zitelbot-target.git 
          echo "************************* upsteam repo added"
      - name: Push to Upstream Repository
        run: |
          git push --mirror upstream
