on:
  push:
    branches:
      - '*'  # Mirror all branches

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Clone Repository with Mirror Flag
        run: |
          git clone --mirror https://github.com/${{ github.repository }}.git
          ls
          cd ${{github.event.repository.name}}.git
          ls
          git remote add upstream https://samHD76:${{ secrets.PAT}}@github.com/samHD76/zitelbot-target.git 

      - name: Push to Upstream Repository
        run: |
          git push --mirror upstream
