on:
  push:
    branches:
      - '*'  # Mirror all branches

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Clone Repository with Mirror Flag
        run: |
          echo "************************cloning!"
          git clone --mirror https://samHD76:${{ secrets.TEST }}@github.com/samHD76/ZitelBot.git
          echo "************************cloned!"
          cd samHD76/ZitelBot.git.git
          echo "*********************************in the directory"
          # git remote add upstream https://samHD76:${{ secrets.PAT }}@github.com/samHD76/zitelbot-target.git
          git remote set-url origin https://github.com/samHD76/zitelbot-target.git
          git remote -v
          echo "************************* upsteam repo added"
          git push --mirror origin
